
CodeQ:
  PublishNotifier:
    senderName: 'Neos Docs Administration'
    senderAddress: 'content.clearing.neos@codeq.at'
    notifyEmails:
      - 'roland@neos.io'
    subject: 'Neos Docs: %1$s has one recommended change'
    body: |+
      %1$s has published changes to the private workspace %2$s.
      Please review the changes and publish to live: https://docs.neos.io%3$s
