
Carbon:
  IncludeAssets:
    GoogleFonts: Material+Icons|Work+Sans:300,200,200italic,300italic,400,400italic
    Packages:
      aa_Theme:
        Path:
          Inline:
            CSS: 'Public/Frontend/build'
            JS: 'Public/Frontend/build'
          File:
            CSS: 'Public/Frontend/build'
            JS: 'Public/Frontend/build'
        # Asset files who get's loaded in live and backend view
        General:
          Head:
            - app.css
          Body:
            - https://code.jquery.com/jquery-3.2.1.min.js
            - materialize.js
            - prism.js
            - app.js
