Flowpack:
  ElasticSearch:
    indexes:
      default:
        'docsneosio-production':    # custom index name, NOTE THIS SHOULD NOT BE HARDCODED ON BEACH
          settings:
            analysis:
              filter:
                autocompleteFilter:
                  max_shingle_size: 4
                  min_shingle_size: 2
                  type: 'shingle'
              analyzer:
                autocomplete:
                  filter: [ 'lowercase', 'autocompleteFilter' ]
                  char_filter: [ 'html_strip' ]
                  type: 'custom'
                  tokenizer: 'standard'

    ContentRepositoryAdaptor:
      driver:
        version: 7.x
